# vim: set ts=2 sts=2 sw=2 expandtab :
dist: xenial
sudo: required
language: bash
services:
  - docker

branches:
  except:
  - gh-pages

before_install:
  - curl -L -o docker-build https://github.com/mate-desktop/mate-dev-scripts/raw/master/travis/docker-build
  - chmod +x docker-build
 
install:
  - sudo apt-get install -y python3-pip python3-setuptools
  - sudo pip3 install --upgrade pip
  - sudo pip install PyGithub
  - ./docker-build --name ${DISTRO} --config .travis.yml --install

script:
  - ./docker-build --name ${DISTRO} --verbose --config .travis.yml --build autotools

env:
  - DISTRO="archlinux/base"
  - DISTRO="debian:sid"
  - DISTRO="fedora:29"
  - DISTRO="ubuntu:18.10"

deploy:
  provider: pages
  github-token: $GITHUB_TOKEN
  #keep-history: true
  target-branch: gh-pages
  local-dir: html-report
  on:
    all_branches: true
    condition: "${DISTRO} =~ ^fedora.*$"

##########################################################
# THE FOLLOWING LINES IS USED BY docker-build
##########################################################
requires:
  archlinux:
    # Useful URL: https://git.archlinux.org/svntogit/community.git/tree/caja
    - gcc
    - git
    - make
    # Append new requires below
    - exempi
    - gobject-introspection
    - gvfs
    - intltool
    - libexif
    - libnotify
    - libsm
    - mate-common
    - mate-desktop
    - which

  debian:
    # Useful URL: https://github.com/mate-desktop/debian-packages
    # Useful URL: https://salsa.debian.org/debian-mate-team/caja
    - git # Required to generate the ChangeLog file
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libnotify-dev
    - libpango1.0-dev
    - libselinux1-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxml2-dev
    - mate-common
    - quilt
    - shared-mime-info

  fedora:
    # Useful URL: https://src.fedoraproject.org/cgit/rpms/caja.git/
    - clang-analyzer # for static analyzer
    - clang          # for static analyzer
    - git
    - gcc
    - make
    - redhat-rpm-config
    - dbus-glib-devel
    - desktop-file-utils
    - exempi-devel
    - gobject-introspection-devel
    - cairo-gobject-devel
    - libexif-devel
    - libselinux-devel
    - libSM-devel
    - libxml2-devel
    - mate-common
    - mate-desktop-devel
    - pangox-compat-devel
    - startup-notification-devel
    - libnotify-devel

  ubuntu:
    # Same as debian
    - git # Required to generate the ChangeLog file
    - gobject-introspection
    - gtk-doc-tools
    - intltool
    - libdconf-dev
    - libexempi-dev
    - libexif-dev
    - libgail-3-dev
    - libgirepository1.0-dev
    - libglib2.0-dev
    - libgtk-3-dev
    - libmate-desktop-dev
    - libnotify-dev
    - libpango1.0-dev
    - libselinux1-dev
    - libstartup-notification0-dev
    - libx11-dev
    - libxml2-dev
    - mate-common
    - quilt
    - shared-mime-info

# Uncomment the following lines to get more compile warnings
variables:
  - CFLAGS="-Wall -Werror=format-security"
  - 'CHECKERS="
    --use-analyzer=`which clang`
    -enable-checker deadcode.DeadStores
    -enable-checker alpha.core.CastSize
    -enable-checker alpha.core.CastToStruct
    -enable-checker alpha.core.IdenticalExpr
    -enable-checker alpha.core.SizeofPtr
    -enable-checker alpha.security.ArrayBoundV2
    -enable-checker alpha.security.MallocOverflow
    -enable-checker alpha.security.ReturnPtrRange
    -enable-checker alpha.unix.SimpleStream
    -enable-checker alpha.unix.cstring.BufferOverlap
    -enable-checker alpha.unix.cstring.NotNullTerminated
    -enable-checker alpha.unix.cstring.OutOfBounds
    -enable-checker alpha.core.FixedAddr
    -enable-checker security.insecureAPI.strcpy"'

after_scripts:
  - if [ ${DISTRO_NAME} == "fedora" ];then
  -     ./autogen.sh
  -     scan-build $CHECKERS --use-analyzer=/usr/bin/clang ./configure
  -     make clean
  -     scan-build $CHECKERS --use-analyzer=/usr/bin/clang --keep-cc -o html-report make
  -     cat > index.html <<EOF
  -     <!DOCTYPE HTML>
  -     <html lang="en">
  -     <head>
  -       <link rel="icon" href="http://mate-desktop.org/favicon.ico" sizes="16x16">
  -       <title>$TRAVIS_REPO_SLUG Code Analizer</title></head>
  -     <body>
  -     <h1>
  -     <a href="https://github.com/$TRAVIS_REPO_SLUG">$TRAVIS_REPO_SLUG</a>
  -     </h1>
  -     <a href="$TRAVIS_BUILD_WEB_URL"><img src="https://travis-ci.org/$TRAVIS_REPO_SLUG.svg?branch=$TRAVIS_BRANCH" alt="Build Status" /></a>
  -     <hr/>
  -     Commit: <a href="https://github.com/$TRAVIS_REPO_SLUG/commit/$TRAVIS_COMMIT">$TRAVIS_COMMIT</a><br/>
  -     Compare: <a href="https://github.com/$TRAVIS_REPO_SLUG/compare/$TRAVIS_COMMIT_RANGE">$TRAVIS_COMMIT_RANGE</a><br/>
  -     Branch: <a href="https://github.com/$TRAVIS_REPO_SLUG/tree/$TRAVIS_BRANCH">$TRAVIS_BRANCH</a><br/>
  -     'Time: `date --rfc-3339=seconds`<br/>'
  -     Messages:<br/>
  -     <pre>
  -     $TRAVIS_COMMIT_MESSAGE
  -     </pre>
  -     <hr/>
  -     <ul>
  -     EOF
  -     for i in `ls html-report`;do
  -       echo "<li><a href=$i>Static analizer result($i)</a></li>" >> index.html
  -     done
  -     echo "</ul>" >> index.html
  -     echo "</body>" >> index.html
  -     echo "</html>" >> index.html
  -     mv index.html html-report
  - fi
  - make distcheck
